### ISSUE TITLE
adding option for slots in sge.tmpl

### ISSUE THREAD

**Issue by yonicd** [wlandau/targets-stan#3]
## Prework

* [x] I understand and agree to this repository's [code of conduct](https://github.com/wlandau/targets-manual/blob/master/CODE_OF_CONDUCT.md).
* [x] I understand and agree to this repository's [contributing guidelines](https://github.com/wlandau/targets-manual/blob/master/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

Please describe the potential feature.

Running concurrent stan models on SGE many times requires using `n` (4) cores (per chain) per job adding

```bash
#$ -pe smp {{slots}}
```

would allow the user to reserve `slots` per job.

To help us read any code you include (optional) please try to follow the [tidyverse style guide](https://style.tidyverse.org/). The `style_text()` and `style_file()` functions from the [`styler`](https://github.com/r-lib/styler) package make it easier.

**Comment by wlandau** [comment]
Just added a line. Definitely a good idea to inform users about. 

The line is commented out because I would prefer not to be too demanding on resources for the default config. (Also, multicore jobs tend to sit a lot longer in the queue.)

**Comment by yonicd** [comment]
understand about the resource demand. 

where is {{slots}} read in from, can that be defaulted to `1` and then could be uncommented?

another option is to write it like this (or the equiv with ifelse in bash, this is from tmpl used by batchtools.future)

```bash
<%= if(!is.null(resources[["slots"]])){
 sprintf('#$ -pe smp %s',resources[["slots"]])
}else{
''
}%>
```

this way if the user doesnt give `slots' that line is skipped.

thanks!

**Comment by yonicd** [comment]
> multicore jobs tend to sit a lot longer in the queue

how does clustermq accommodate parallel chain runs then, this would come up in nearly every stan run wouldnt it?

**Comment by wlandau** [comment]
> where is {{slots}} read in from, can that be defaulted to 1 and then could be uncommented?

Yeah, good point about defaults. The line `#$ -pe smp {{ slots | 1 }}` already says to default to 1 if `slots` is not set. Uncommented in the latest commit. To request multiple slots, you would write `tar_make_clustermq(template = list(slots = 4))`.

**Comment by yonicd** [comment]
cool. thanks!

**Comment by wlandau** [comment]
> how does clustermq accommodate parallel chain runs then, this would come up in nearly every stan run wouldnt it?

For this workflow, there is no need to accommodate parallel chains. What we really want is parallel *models*. To validate the model, we call `fit_model()` thousands of times, and each call to `fit_model()` only has 3 or 4 chains.
