### ISSUE TITLE
Suggestion: use cmdstanr rather than rstan

### ISSUE THREAD

**Issue by mike-lawrence** [wlandau/targets-stan#7]
I think the Stan devs are gradually shifting to recommending folks use cmdstanr rather than rstan because the latter always has trouble with CRAN and is often far behind in features, whereas cmdstanr can pull the very latest cmdstan. It's now in beta, but the devs say that no current features will disappear, but instead go through a proper deprecation cycle.

**Comment by wlandau** [comment]
Great suggestion. I think I'll want to wait until it is on CRAN, but I totally agree that switching is a good idea. 

I actually wanted to use `cmdstanr` for a recent project at work but had some issues getting the CmdStan executables to ship with the project's portable `renv` library. We ended up creating an `rstantools`-powered package with a pre-compiled model instead.

**Comment by wlandau** [comment]
So I will close the issue until `cmdstanr` is published, then work on some new installation recommendations for the purpose of this little example. Feel free to ping me if I miss the `cmdstanr` release.
